/* Redux Action Names */

/* POST HTTP requests */
const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS'; // '/bookmark'
const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';
const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS'; // '/folder'
const ADD_FOLDER_ERROR = 'ADD_FOLDER_ERROR';

/* GET HTTP requests */
const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS'; // '/bookmarks'
const GET_BOOKMARKS_ERROR = 'GET_BOOKMARKS_ERROR';
const GET_FOLDERS_SUCCESS = 'GET_FOLDERS_SUCCESS'; // '/folders'
const GET_FOLDERS_ERROR = 'GET_FOLDERS_ERROR';
const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'; // '/tags'
const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
const GET_BOOKMARKS_BY_FOLDER_SUCCESS = 'GET_BOOKMARKS_BY_FOLDER_SUCCESS'; // '/bookmarks/:folderName'
const GET_BOOKMARKS_BY_FOLDER_ERROR = 'GET_BOOKMARKS_BY_FOLDER_ERROR';
const GET_BOOKMARKS_BY_TAG_SUCCESS = 'GET_BOOKMARKS_BY_TAG_SUCCESS'; // '/bookmarks/:tagName'
const GET_BOOKMARKS_BY_TAG_ERROR = 'GET_BOOKMARKS_BY_TAG_ERROR';

/* PUT HTTP requests */
const EDIT_BOOKMARK_SUCCESS = 'EDIT_BOOKMARK_SUCCESS'; // '/bookmark/:id'
const EDIT_BOOKMARK_ERROR = 'EDIT_BOOKMARK_ERROR';

/* DELETE HTTP requests */
const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS'; // '/bookmark/:id'
const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';

exports.ADD_BOOKMARK_SUCCESS = ADD_BOOKMARK_SUCCESS;
exports.ADD_BOOKMARK_ERROR = ADD_BOOKMARK_ERROR;
exports.ADD_FOLDER_SUCCESS = ADD_FOLDER_SUCCESS;
exports.ADD_FOLDER_ERROR = ADD_FOLDER_ERROR;
exports.ADD_FOLDER_SUCCESS = ADD_FOLDER_SUCCESS;
exports.ADD_BOOKMARK_ERROR = ADD_BOOKMARK_ERROR;
exports.GET_BOOKMARKS_SUCCESS = GET_BOOKMARKS_SUCCESS;
exports.GET_BOOKMARKS_ERROR = GET_BOOKMARKS_ERROR;
exports.GET_FOLDERS_SUCCESS = GET_FOLDERS_SUCCESS;
exports.GET_FOLDERS_ERROR = GET_FOLDERS_ERROR;
exports.GET_TAGS_SUCCESS = GET_TAGS_SUCCESS;
exports.GET_TAGS_ERROR = GET_TAGS_ERROR;
exports.GET_BOOKMARKS_BY_FOLDER_SUCCESS = GET_BOOKMARKS_BY_FOLDER_SUCCESS;
exports.GET_BOOKMARKS_BY_FOLDER_ERROR = GET_BOOKMARKS_BY_FOLDER_ERROR;
exports.GET_BOOKMARKS_BY_TAG_SUCCESS = GET_BOOKMARKS_BY_TAG_SUCCESS;
exports.GET_BOOKMARKS_BY_TAG_ERROR = GET_BOOKMARKS_BY_TAG_ERROR;
exports.EDIT_BOOKMARK_SUCCESS = EDIT_BOOKMARK_SUCCESS;
exports.EDIT_BOOKMARK_ERROR = EDIT_BOOKMARK_ERROR;
exports.DELETE_BOOKMARK_SUCCESS = DELETE_BOOKMARK_SUCCESS;
exports.DELETE_BOOKMARK_ERROR = DELETE_BOOKMARK_ERROR;
// exports.LOAD_BOOKMARK_FORM = LOAD_BOOKMARK_FORM;
// exports.VIEW_BOOKMARK = VIEW_BOOKMARK;
// exports.CLOSE_BOOKMARK = CLOSE_BOOKMARK;
// exports.CONFIRM_DELETE_BOOKMARK = CONFIRM_DELETE_BOOKMARK;
