/* Redux Action Names */

/* POST HTTP requests */
const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';
const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS';
const ADD_FOLDER_ERROR = 'ADD_FOLDER_ERROR';

/* GET HTTP requests */
const GET_BOOKMARKS_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
const GET_BOOKMARKS_ERROR = 'ADD_BOOKMARK_ERROR';
const GET_FOLDERS_SUCCESS = 'ADD_FOLDER_SUCCESS';
const GET_FOLDERS_ERROR = 'ADD_FOLDER_ERROR';
const GET_BOOKMARKS_BY_FOLDER_SUCCESS = 'GET_BOOKMARKS_BY_FOLDER_SUCCESS';
const GET_BOOKMARKS_BY_FOLDER_ERROR = 'GET_BOOKMARKS_BY_FOLDER_ERROR';
const GET_BOOKMARKS_BY_TAG_SUCCESS = 'GET_BOOKMARKS_BY_TAG_SUCCESS';
const GET_BOOKMARKS_BY_TAG_ERROR = 'GET_BOOKMARKS_BY_TAG_ERROR';

/* PUT HTTP requests */
const EDIT_BOOKMARK_SUCCESS = 'EDIT_BOOKMARK_SUCCESS';
const EDIT_BOOKMARK_ERROR = 'EDIT_BOOKMARK_ERROR';

/* DELETE HTTP requests */
const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';

/* UI changes */
// const LOAD_BOOKMARK_FORM = 'LOAD_BOOKMARK_FORM';
// const VIEW_BOOKMARK = 'VIEW_BOOKMARK';
// const CLOSE_BOOKMARK = 'CLOSE_BOOKMARK';
const CONFIRM_DELETE_BOOKMARK = 'CONFIRM_DELETE_BOOKMARK';

exports.ADD_FOLDER_SUCCESS = ADD_FOLDER_SUCCESS;
exports.ADD_BOOKMARK_ERROR = ADD_BOOKMARK_ERROR;
exports.ADD_FOLDER_SUCCESS = ADD_FOLDER_SUCCESS;
exports.ADD_BOOKMARK_ERROR = ADD_BOOKMARK_ERROR;
exports.GET_BOOKMARKS_SUCCESS = GET_BOOKMARKS_SUCCESS;
exports.GET_BOOKMARKS_ERROR = GET_BOOKMARKS_ERROR;
exports.GET_FOLDERS_SUCCESS = GET_FOLDERS_SUCCESS;
exports.GET_FOLDERS_ERROR = GET_FOLDERS_ERROR;
exports.GET_BOOKMARKS_BY_FOLDER_SUCCESS = GET_BOOKMARKS_BY_FOLDER_SUCCESS;
exports.GET_BOOKMARKS_BY_FOLDER_ERROR = GET_BOOKMARKS_BY_FOLDER_ERROR;
exports.GET_BOOKMARKS_BY_TAG_SUCCESS = GET_BOOKMARKS_BY_TAG_SUCCESS;
exports.GET_BOOKMARKS_BY_TAG_ERROR = GET_BOOKMARKS_BY_TAG_ERROR;
exports.EDIT_BOOKMARK_SUCCESS = EDIT_BOOKMARK_SUCCESS;
exports.EDIT_BOOKMARK_ERROR = EDIT_BOOKMARK_ERROR;
exports.DELETE_BOOKMARK_SUCCESS = DELETE_BOOKMARK_SUCCESS;
exports.DELETE_BOOKMARK_ERROR = DELETE_BOOKMARK_ERROR;
exports.LOAD_BOOKMARK_FORM = LOAD_BOOKMARK_FORM;
exports.VIEW_BOOKMARK = VIEW_BOOKMARK;
exports.CLOSE_BOOKMARK = CLOSE_BOOKMARK;
exports.CONFIRM_DELETE_BOOKMARK = CONFIRM_DELETE_BOOKMARK;